name: 'sync Upstream'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'updateUpstream'
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        ls -a
        git clone https://github.com/ruleihui/goindex-theme-acrou.git
        cd goindex-theme-acrou/
        git config --global user.email "879903786@qq.com"
        git config --global user.username "ruleihui"
        git config --global user.password $API_TOKEN_GITHUB
        git remote -v
        git checkout master
        git remote add upstream https://github.com/Aicirou/goindex-theme-acrou.git
        git remote -v
        git fetch upstream
        git merge upstream/master -m "update"
        git push origin master
      
