name: 'sync Upstream'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'updateUpstream'
      env:
        HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
        HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
      run: |
        ls -a
        git remote -v
        git checkout master
        git remote -add upstream https://github.com/Aicirou/goindex-theme-acrou.git
        git remote -v
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push origin master
      
